### ISSUE TITLE
Disable only one analog stick

### ISSUE THREAD

**Issue by zobu312** [Hack-Usagi/AnalogStickDisable#1]
Thank you for this plugin. It is great for the Vita I have that has stick issue even when replaced countless times. I have a request though, can you make it so only one of the sticks be disabled? Like just the left or the right one.

**Comment by Hack-Usagi** [comment]
Thank you for your opinion.
In the next version, upload right / left / both:)

**Comment by Hack-Usagi** [comment]
Ver1.1 has been released.
